import type { ReactElement } from "react";
import Link from "next/link";

export default function TermsPage(): ReactElement {
  return (
    <div className="min-h-screen bg-[var(--surface-page)]">
      <div className="mx-auto max-w-3xl px-4 py-12">
        {/* Back link */}
        <div className="mb-8">
          <Link
            href="/"
            className="text-sm text-[var(--text-link)] underline-offset-2 hover:text-[var(--text-link-hover)] hover:underline"
          >
            ← CFO Lens
          </Link>
        </div>

        {/* Header */}
        <h1 className="text-3xl font-semibold text-[var(--text-primary)]">Terms of Service</h1>
        <p className="mt-2 text-sm text-[var(--text-muted)]">Last updated: July 2026</p>
        <p className="mt-4 leading-relaxed text-[var(--text-secondary)]">
          Please read these Terms of Service carefully before using CFO Lens. By accessing or using
          the product, you agree to be bound by these Terms.
        </p>

        {/* 1. Acceptance of Terms */}
        <section className="mt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            1. Acceptance of Terms
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            By accessing or using CFO Lens, you agree to be bound by these Terms of Service and all
            applicable laws and regulations. If you do not agree with any of these Terms, you are
            prohibited from using this product. These Terms constitute a legally binding agreement
            between you and CFO Lens. Your continued use of the product following any update to
            these Terms constitutes acceptance of those changes.
          </p>
        </section>

        {/* 2. Description of Service */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            2. Description of Service
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            CFO Lens provides AI-powered financial intelligence for small and medium-sized
            businesses. The product connects to your QuickBooks Online or Xero account to read your
            accounting data, generates findings and cash flow projections, and enables
            conversational financial queries. The product is designed to supplement — not replace —
            professional financial advice and qualified human judgment.
          </p>
        </section>

        {/* 3. Not Financial Advice — REQUIRED */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            3. Not Financial Advice
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            The analysis, projections, and findings provided by this product are generated by AI and
            are based on your accounting data. They do not constitute financial, investment, tax, or
            legal advice. Do not make decisions based solely on this analysis without consulting a
            qualified financial professional.
          </p>
        </section>

        {/* 4. Data Sovereignty — REQUIRED */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">4. Data Sovereignty</h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            This product has read-only access to your QuickBooks and Xero accounting data. We never
            write to, modify, or delete records in your accounting system. Your financial records
            remain entirely under your control. If you disconnect or cancel, your books are
            unchanged. You can export all data this service has generated at any time from Settings
            → Account.
          </p>
        </section>

        {/* 5. User Responsibilities */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            5. User Responsibilities
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            You are responsible for maintaining the accuracy of your underlying accounting data in
            QuickBooks, Xero, or any CSV files you upload. You agree to use this product only for
            lawful business purposes. You are responsible for maintaining the confidentiality of
            your account credentials and for all activity that occurs under your account. You must
            promptly notify us of any unauthorized use of your account.
          </p>
        </section>

        {/* 6. Subscription and Billing */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            6. Subscription and Billing
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            CFO Lens is offered on a subscription basis. By providing a payment method, you
            authorize us to charge your payment method on a recurring basis for the applicable
            subscription fee. Subscriptions renew automatically until cancelled. You may cancel at
            any time from Settings → Account; cancellation takes effect at the end of the current
            billing period. Fees are non-refundable except where required by applicable law.
          </p>
        </section>

        {/* 7. Intellectual Property */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            7. Intellectual Property
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            The software, design, and original content of CFO Lens are our property and are
            protected by applicable intellectual property laws. Your financial data, accounting
            records, and any reports generated from your data belong to you. We claim no ownership
            over your business information. The AI-generated analysis, findings, and draft
            communications created using your data are yours to use as you see fit.
          </p>
        </section>

        {/* 8. Limitation of Liability */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            8. Limitation of Liability
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            To the fullest extent permitted by applicable law, our total liability for any claim
            arising from your use of this product is limited to the subscription fees you paid in
            the twelve months immediately preceding the claim. We are not liable for indirect,
            incidental, special, or consequential damages — including lost profits, lost data, or
            business interruption — even if we have been advised of the possibility of such damages.
            The limitations in this section apply regardless of the theory of liability (contract,
            tort, or otherwise).
          </p>
        </section>

        {/* 9. Termination */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">9. Termination</h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            You may cancel your account at any time from Settings → Account. We reserve the right to
            suspend or terminate your access for violation of these Terms, at our sole discretion,
            with or without notice. Upon account closure, you have thirty days to export your data
            from Settings → Account before it is permanently deleted. Cancellation does not entitle
            you to a refund for any unused portion of a prepaid subscription period.
          </p>
        </section>

        {/* 10. Changes to These Terms */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">
            10. Changes to These Terms
          </h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            We will notify you via email of any material changes to these Terms at least fourteen
            days before they take effect. Minor clarifications or changes that do not materially
            affect your rights may be made without notice. The current version of these Terms is
            always available at this URL.
          </p>
        </section>

        {/* 11. Governing Law */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">11. Governing Law</h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            These Terms are governed by and construed in accordance with applicable law. Any dispute
            arising from these Terms or your use of the product shall be resolved through binding
            arbitration in accordance with the rules of the American Arbitration Association, except
            where prohibited by law. Nothing in this section prevents either party from seeking
            injunctive relief in a court of competent jurisdiction.
          </p>
        </section>

        {/* 12. Contact */}
        <section className="mt-8 border-t border-[var(--border-default)] pt-8">
          <h2 className="text-xl font-semibold text-[var(--text-primary)]">12. Contact</h2>
          <p className="mt-3 leading-relaxed text-[var(--text-secondary)]">
            Questions about these Terms? Email us at{" "}
            <a
              href="mailto:legal@cfolens.com"
              className="text-[var(--text-link)] underline underline-offset-2 hover:text-[var(--text-link-hover)]"
            >
              legal@cfolens.com
            </a>
            . You may also review our{" "}
            <Link
              href="/privacy"
              className="text-[var(--text-link)] underline underline-offset-2 hover:text-[var(--text-link-hover)]"
            >
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        {/* Footer */}
        <p className="mt-12 text-xs text-[var(--text-muted)]">
          © 2026 CFO Lens. All rights reserved.
        </p>
      </div>
    </div>
  );
}
